general.import = [
#    "~/.config/alacritty/themes/themes/ayu_light.toml"
    ]

[font]
size = 20.0

[font.bold]
family = "JetBrains Mono"
style = "Bold"

[font.bold_italic]
family = "JetBrains Mono"
style = "Bold Italic"

[font.italic]
family = "JetBrains Mono"
style = "Italic"

[font.normal]
family = "JetBrains Mono"
style = "Regular"



[window]
padding = { x = 3, y = 3 }
dynamic_padding = true
opacity = 0.7
startup_mode = "Fullscreen"

[terminal.shell]
program = "/bin/zsh"

