# ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
# ┃                     Defaults Configuration                  ┃
# ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛


# General
$filemanager = nautilus 
$applauncher = wofi
$terminal = alacritty
#$idlehandler = swayidle -w timeout 300 'swaylock -f -c 000000' before-sleep 'swaylock -f -c 000000'

# Screenshots using grim + slurp
#$shot-region = grimblast copy area
#$shot-window = grimblast copy active
#$shot-screen = grimblast copy screen

$shot-region = /home/angloong/.config/hypr/scripts/screenshot.sh # 使用相对路径不可用，$HOME未试
$shot-screen = /home/angloong/.config/hypr/scripts/screenshot.sh full

