# ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
# ┃                    Enviroment Configuration                 ┃
# ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛

env = XCURSOR_SIZE,34
env = HYPRCURSOR_THEME,"Future-Cyan-Hyprcursor_Theme
env = HYPRCURSOR_SIZE,45
#env = QT_CURSOR_SIZE,34
